---
- hosts: k8s-master
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  tasks:
   - name: copy k8s files
     copy:
       src: "{{ item }}"
       dest: /tmp/
     loop:
      - deployment.yml
      - service.yml
   - name: create deployment
     shell: export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f deployment.yml
     args:
       chdir: /tmp/
   - name: create service
     shell: export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f service.yml
     args:
       chdir: /tmp/
