apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
  labels:
    type: app
    env: prod
spec:
  containers:
   - name: springboot-petclinic-app
     image: itpurush/springboot-petclinic-app:1.0
