apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
        type: NodePort
        ports:
                - targetPort: 8080
                  port: 8080
                  nodePort: 30004
        selector:
          type: app
          env: prod
